In [1]:
import numpy as np

In [7]:
my_list=[[1,2,3],[4,5,6]]

In [8]:
ar=np.array(my_list)

In [9]:
print(ar)

[[1 2 3]
 [4 5 6]]


In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros([5,6],dtype=np.int32)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [17]:
ar1=np.linspace(0,10,3)
print(ar1)

[ 0.  5. 10.]


In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.empty([5,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.random.rand(2)

array([0.33678042, 0.11262926])

In [21]:
np.random.randint(1,6,5)

array([1, 5, 4, 5, 1])

In [22]:
arr=np.arange(25)
rarr=np.random.randint(0,50,10)

In [24]:
print(arr)
print(rarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[44 30 11 43 13  9 36  2 24 25]


In [30]:
xp=arr.reshape(5,5)
print(xp)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [31]:
import pandas as pd

In [32]:
pd1=pd.DataFrame(xp)
print(pd1)

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


In [35]:
labels=['a','b','c']
my_list=[1,2,3]
arl=np.array([10,20,30])
d={'a':10,'b':20,'c':30}

In [34]:
pd.Series(my_list)

0    [1, 2, 3]
1    [4, 5, 6]
dtype: object

In [36]:
pd.Series(labels,my_list)

1    a
2    b
3    c
dtype: object

In [37]:
pd.Series(my_list,labels)

a    1
b    2
c    3
dtype: int64

In [38]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [41]:
a1=pd.Series([1,2,3,4],['USA','GERMANY','USSR','JAPAN'])

In [42]:
a2=pd.Series([1,2,5,4],['USA','GERMANY','ITALY','JAPAN'])

In [43]:
a1+a2

GERMANY    4.0
ITALY      NaN
JAPAN      8.0
USA        2.0
USSR       NaN
dtype: float64

In [51]:
"A B C D".split()

['A', 'B', 'C', 'D']

In [2]:
from numpy.random import randn
np.random.seed(101)
print(x)

NameError: name 'np' is not defined

In [3]:
df=pd.DataFrame(randn(5,4),index="A B C D E".split(),columns="W X Y Z".split())
print(df)

NameError: name 'pd' is not defined